server {
  listen 8080;
  server_name _;

  location = /healthz {
    access_log off;
    default_type text/plain;
    return 200 "ok\n";
  }

  location / {
    root /usr/share/nginx/html;
    index index.html;
  }

  location /api/ {
    proxy_pass http://app02-service.app02-weekend-com.svc.cluster.local/;
  }

  location /app03/ {
    proxy_pass http://app03-service.app03-weekend-com.svc.cluster.local/;
  }
}
